version: '3.8'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/appFrontend
