version: '3.8'

services:
  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
